### PR TITLE
Upgraded Angular to 14.2

### PR DESCRIPTION
**Pull request by RatGabi**
https://filestack.atlassian.net/browse/FS-10981
Tests work
image

### CODE REVIEW

**Review by sethk4783 — APPROVED** [review]
LGTM

**Comment by FearMichael** [comment]
Is there anything preventing this from being merged? This repo is woefully behind and this would be a great enhancement.

**Comment by MAGNUM81** [comment]
@RatGabi status?

**Comment by FearMichael** [comment]
Can we get this merged? This repo has been behind for years.

**Pull request merged**
